# Generated by Django 6.0.2 on 2026-02-23 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('attendance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('overtime', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prepaid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_to_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payroll.payrollrun')),
            ],
            options={
                'ordering': ['employee__first_name'],
                'unique_together': {('run', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='PrepaidEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prepaids', to='employees.employee')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'year', 'month', 'note')},
            },
        ),
    ]
