# Generated by Django 6.0.2 on 2026-02-23 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('SHIFT_OFF', 'Shift Off'), ('HOLIDAY', 'Holiday'), ('FRIDAY', 'Friday')], default='PRESENT', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_days', to='employees.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__first_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
