# Generated by Django 6.0.2 on 2026-02-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceday',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('SHIFT_OFF', 'Shift Off'), ('HOLIDAY', 'Holiday'), ('LEAVE', 'Leave')], default='PRESENT', max_length=20),
        ),
    ]
