# Generated by Django 6.0.2 on 2026-02-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='auto_cover_absence',
            field=models.BooleanField(default=False),
        ),
    ]
