# Generated by Django 6.0.2 on 2026-02-23 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leavetype_auto_cover_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveentry',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveentry',
            name='days_count',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
