# Generated by Django 6.0.2 on 2026-02-23 05:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('holidays_count', models.PositiveSmallIntegerField(default=0)),
                ('overtime_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('daily_work_hours', models.DecimalField(decimal_places=2, default=8, max_digits=5)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
    ]
