# Generated by Django 6.0.2 on 2026-02-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthconfig',
            name='monthly_paid_leave_cap',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='monthconfig',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
