# Generated by Django 6.0.2 on 2026-02-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_monthconfig_monthly_paid_leave_cap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthconfig',
            name='holidays_count',
        ),
    ]
