# Generated by Django 6.0.2 on 2026-02-23 05:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('father_name', models.CharField(blank=True, max_length=80)),
                ('employee_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACT', 'Contract'), ('DAILY', 'Daily Worker'), ('FIXED_TERM', 'Fixed Term')], max_length=20)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('date_hired', models.DateField()),
                ('status', models.CharField(choices=[('WORKING', 'Working'), ('SUSPENDED', 'Suspended'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='WORKING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='org.position')),
            ],
            options={
                'ordering': ['first_name', 'father_name'],
            },
        ),
    ]
